call_me_web_homepage:
    pattern:  /
    defaults: { _controller: CallMeWebBundle:Default:index }

register_page:
    pattern:     /register
    defaults: { _controller: CallMeWebBundle:Default:register }

process_register:
    pattern:     /process-register
    defaults: { _controller: CallMeWebBundle:Default:processRegister }

login:
    pattern: /login
    defaults: { _controller: CallMeWebBundle:Security:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout

forgot_password:
    pattern: /forgot-password
    defaults: { _controller: CallMeWebBundle:Security:forgotPassword }

process_forgot_password:
    pattern: /process-forgot-password
    defaults: { _controller: CallMeWebBundle:Security:processForgotPassword }
    methods: [POST]

reset_password:
    pattern: /reset-password/{token}/{hashedEmail}
    defaults: { _controller: CallMeWebBundle:Security:resetPassword }
    methods: [GET]

process_reset_password:
    pattern: /process-reset-password
    defaults: { _controller: CallMeWebBundle:Security:processResetPassword }
    methods: [POST]

user_settings:
   pattern: /settings
   defaults: { _controller: CallMeWebBundle:User:settings }
   methods: [GET]

process_user_settings:
   pattern: /process-user-settings
   defaults: { _controller: CallMeWebBundle:User:processSettings }
   methods: [POST]

audio_index:
    pattern: /audio
    defaults: { _controller: CallMeWebBundle:Audio:index }
    methods: [GET]

audio_upload:
    pattern: /audio/upload
    defaults: { _controller: CallMeWebBundle:Audio:uploadAudio }
    methods: [POST]

make_call:
    pattern: /phone/demo
    defaults: { _controller: CallMeWebBundle:Phone:call }
    methods: [GET]

dial_call:
    pattern: /phone/demo/call
    defaults: { _controller: CallMeWebBundle:Phone:processCall }
    methods: [POST]

dial_callback:
    pattern: /phone/demo/callback
    defaults: { _controller: CallMeWebBundle:Phone:processCallBack }
    methods: [POST]

dial_message:
    pattern: /phone/demo/message
    defaults: { _controller: CallMeWebBundle:Phone:processMessage }
    methods: [POST]

dashboard_index:
    pattern: /dashboard
    defaults: { _controller: CallMeWebBundle:Default:dashboard }
    methods: [GET]
